export const modelRegistry = [
  { 
    id: 'Llama-3.2-1B-Instruct-q4f16_1-MLC', 
    name: 'Llama 3.2', 
    size: '1B Param', 
    cached: false, 
    loading: false, 
    progress: 0, 
    score: 1200,
    backend: 'webgpu',
    category: 'Text-Chat-Modelle',
    status: 'active',
    description: 'Solider Allrounder von Meta. Gute Balance zwischen Speed und Wissen.',
    strengths: ['Vielseitig einsetzbar', 'Hohe Kontext-Stabilität', 'Starke Community'],
    weaknesses: ['Teilweise wortreich', 'Logik schwächer als SmolLM2']
  },
  { 
    id: 'Qwen2-1.5B-Instruct-q4f16_1-MLC', 
    name: 'Qwen 2', 
    size: '1.5B Param', 
    cached: false, 
    loading: false, 
    progress: 0, 
    score: 1150,
    backend: 'webgpu',
    language: 'Multilingual',
    license: 'Apache 2.0',
    category: 'Text-Chat-Modelle',
    status: 'active',
    description: 'Effizientes Modell von Alibaba, spezialisiert auf Instruktionen.',
    strengths: ['Stark in Mehrsprachigkeit', 'Exzellente Befolgung von Anweisungen', 'Sehr kompakt'],
    weaknesses: ['Begrenztes Weltwissen']
  },
  { 
    id: 'TinyLlama-1.1B-Chat-v1.0-q4f16_1-MLC', 
    name: 'TinyLlama', 
    size: '1.1B Param', 
    cached: false, 
    loading: false, 
    progress: 0, 
    score: 1000,
    backend: 'webgpu',
    language: 'English',
    license: 'MIT',
    category: 'Mini-Reasoning',
    status: 'active',
    description: 'Der Geschwindigkeits-König für einfachste Interaktionen.',
    strengths: ['Extrem schnell', 'Minimaler RAM-Bedarf', 'Stabil auf Mobile'],
    weaknesses: ['Schwache Logik', 'Neigt zu Halluzinationen']
  },
  { 
    id: 'Gemma-2B-it-q4f16_1-MLC', 
    name: 'Gemma', 
    size: '2B Param', 
    cached: false, 
    loading: false, 
    progress: 0, 
    score: 1250,
    backend: 'webgpu',
    language: 'Multilingual',
    license: 'Gemma',
    category: 'Text-Chat-Modelle',
    status: 'active',
    description: 'Googles Premium-Modell für hohe Textqualität und Logik.',
    strengths: ['Überlegene Reasoning-Fähigkeit', 'Hohe sprachliche Nuancen', 'Sehr präzise'],
    weaknesses: ['Höchster RAM-Bedarf im Portfolio', 'Langsamerer Output']
  },
  { 
    id: 'SmolLM2-1.7B-Instruct-q4f16_1-MLC', 
    name: 'SmolLM2', 
    size: '1.7B Param', 
    cached: false, 
    loading: false, 
    progress: 0, 
    score: 1100,
    backend: 'webgpu',
    language: 'English',
    license: 'Apache 2.0',
    category: 'Text-Chat-Modelle',
    status: 'active',
    description: 'Spezialisiert auf Logik und STEM durch kuratierte Trainingsdaten.',
    strengths: ['Exzellent in Mathe & Logik', 'Sehr hohe Faktentreue', 'Präzise Antworten'],
    weaknesses: ['Fokus auf Englisch']
  },
  { 
    id: 'Qwen2.5-0.5B-Instruct-q4f16_1-MLC', 
    name: 'Qwen 2.5 Tiny', 
    size: '0.5B Param', 
    cached: false, 
    loading: false, 
    progress: 0, 
    score: 1050,
    backend: 'webgpu',
    language: 'Multilingual',
    license: 'Apache 2.0',
    category: 'Mini-Reasoning',
    status: 'active',
    description: 'Das Effizienz-Wunder für einfachste Aufgaben.',
    strengths: ['Läuft fast überall', 'Schnellste Reaktion', 'Gute Mehrsprachigkeit'],
    weaknesses: ['Wenig Weltwissen', 'Einfache Logik']
  }
];
