export const modelRegistry = [
  // ─── Aktive Arena-Modelle (2025/2026 Generation) ───────────────────────
  { 
    id: 'Qwen3.5-4B-q4f16_1-MLC', 
    name: 'Qwen3.5 4B', 
    type: 'text',
    loader: 'mlc',
    arena: true,
    size: '4B Param', 
    cached: false, 
    loading: false, 
    progress: 0, 
    score: 1340,
    backend: 'webgpu',
    category: 'Flagship-Klasse',
    badge: 'Flagship',
    status: 'active',
    description: 'Das neue Flaggschiff (2026). Vision-fähig, 262k Kontext und Top-Benchmarks (GPQA 76.2) – schlägt viele 20B-Klassen-Modelle.',
    strengths: ['Neueste Generation', 'Vision & Text', 'Stärkstes Modell im Browser'],
    weaknesses: ['Etwas über dem 3B-Limit', 'Höchster VRAM-Bedarf']
  },
  { 
    id: 'Phi-4-mini-instruct-q4f16_1-MLC', 
    name: 'Phi-4 mini', 
    type: 'text',
    loader: 'mlc',
    arena: true,
    size: '3.8B Param', 
    cached: false, 
    loading: false, 
    progress: 0, 
    score: 1330,
    backend: 'webgpu',
    category: 'Reasoning-Klasse',
    badge: 'Reasoning',
    status: 'active',
    description: 'Microsofts Reasoning-Spezialist. Extrem starke Logik und Mathematik für die Sub-4B-Klasse.',
    strengths: ['Überlegene Logik & Mathematik', 'Präzises Instruction-Following'],
    weaknesses: ['Etwas über dem 3B-Limit']
  },
  { 
    id: 'Ministral-3-3B-Instruct-2512-BF16-q4f16_1-MLC', 
    name: 'Ministral 3 3B', 
    type: 'text',
    loader: 'mlc',
    arena: true,
    size: '3B Param', 
    cached: false, 
    loading: false, 
    progress: 0, 
    score: 1325,
    backend: 'webgpu',
    category: 'Reasoning-Klasse',
    badge: 'Champion',
    status: 'active',
    description: 'Mistral aktueller Champion (12/2025). Modernste Architektur mit exzellentem Instruction-Following.',
    strengths: ['Neueste Mistral-Architektur', 'Sehr gutes Sprachgefühl', 'Stark in Anweisungen'],
    weaknesses: ['Noch wenig Browser-Historie']
  },
  { 
    id: 'Hermes-3-Llama-3.2-3B-q4f16_1-MLC', 
    name: 'Hermes 3 3B', 
    type: 'text',
    loader: 'mlc',
    arena: true,
    size: '3B Param', 
    cached: false, 
    loading: false, 
    progress: 0, 
    score: 1315,
    backend: 'webgpu',
    category: 'Reasoning-Klasse',
    badge: 'Champion',
    status: 'active',
    description: 'Nous-Research-Finetune des alten Champions. Deutlich stärkere Reasoning-Fähigkeiten als Llama 3.2 3B.',
    strengths: ['Besser als Llama 3.2 3B', 'Starke Tool-Nutzung', 'Vielseitig'],
    weaknesses: ['Höherer VRAM-Bedarf']
  },
  { 
    id: 'Qwen3.5-2B-q4f16_1-MLC', 
    name: 'Qwen3.5 2B', 
    type: 'text',
    loader: 'mlc',
    arena: true,
    size: '2B Param', 
    cached: false, 
    loading: false, 
    progress: 0, 
    score: 1305,
    backend: 'webgpu',
    category: 'Allround-Klasse',
    badge: 'Balanced',
    status: 'active',
    description: '2026er-Generation im kompakten Format. Vision-fähig und enorm sprachsicher für die 2B-Klasse.',
    strengths: ['Sehr schnell', 'Vision & Text', 'Exzellente Mehrsprachigkeit'],
    weaknesses: ['Weniger Weltwissen als 4B']
  },
  { 
    id: 'Ministral-3-3B-Reasoning-2512-q4f16_1-MLC', 
    name: 'Ministral 3 Reasoning', 
    type: 'text',
    loader: 'mlc',
    arena: true,
    size: '3B Param', 
    cached: false, 
    loading: false, 
    progress: 0, 
    score: 1300,
    backend: 'webgpu',
    category: 'Thinking-Klasse',
    badge: 'Thinking',
    status: 'active',
    description: 'Reasoning-Variante von Mistral. Denkt in Chain-of-Thought-Schritten – ideal für logische Arena-Duelle.',
    strengths: ['Chain-of-Thought-Reasoning', 'Starke Logik', 'Hohe Faktentreue'],
    weaknesses: ['Langsamerer Token-Fluss', 'Denkschritte kosten Tokens']
  },
  { 
    id: 'Qwen3-1.7B-q4f16_1-MLC', 
    name: 'Qwen3 1.7B', 
    type: 'text',
    loader: 'mlc',
    arena: true,
    size: '1.7B Param', 
    cached: false, 
    loading: false, 
    progress: 0, 
    score: 1290,
    backend: 'webgpu',
    category: 'Thinking-Klasse',
    badge: 'Thinking',
    status: 'active',
    description: 'Qwen3 mit schaltbarem Thinking-Modus. Deutlich stärker als SmolLM2 und Qwen2.5 in gleicher Größe.',
    strengths: ['Thinking-Modus (CoT)', 'Stark in Mathe & Code', 'Schnell'],
    weaknesses: ['Denkschritte kosten Tokens']
  },
  { 
    id: 'Qwen2.5-3B-Instruct-q4f16_1-MLC', 
    name: 'Qwen 2.5 3B', 
    type: 'text',
    loader: 'mlc',
    arena: true,
    size: '3B Param', 
    cached: false, 
    loading: false, 
    progress: 0, 
    score: 1280,
    backend: 'webgpu',
    category: 'Allround-Klasse',
    badge: 'Balanced',
    status: 'active',
    description: 'Der solide Allrounder im 3B-Limit. Exzellente Mehrsprachigkeit und präzises Instruction-Following.',
    strengths: ['Starke Mehrsprachigkeit', 'Präzises Instruction-Following', 'Gutes Weltwissen'],
    weaknesses: ['Kein Thinking-Modus']
  },
  { 
    id: 'gemma3-1b-it-q4f16_1-MLC', 
    name: 'Gemma 3 1B', 
    type: 'text',
    loader: 'mlc',
    arena: true,
    size: '1B Param', 
    cached: false, 
    loading: false, 
    progress: 0, 
    score: 1240,
    backend: 'webgpu',
    category: 'Speed-Klasse',
    badge: 'Speed',
    status: 'active',
    description: 'Googles neue 1B-Generation. Modernere Architektur als Gemma 2 bei minimalem Speicherbedarf.',
    strengths: ['Läuft fast überall', 'Sehr schnell', 'Gutes Sprachgefühl'],
    weaknesses: ['Wenig Weltwissen']
  },
  // ─── Archiv (2023/2024 Generation, ausgemustert) ───────────────────────
  { 
    id: 'Llama-3.2-3B-Instruct-q4f16_1-MLC', 
    name: 'Llama 3.2 3B', 
    type: 'text',
    loader: 'mlc',
    arena: false,
    size: '3B Param', 
    cached: false, 
    loading: false, 
    progress: 0, 
    score: 1300,
    backend: 'webgpu',
    category: 'Archiv',
    badge: 'Retired',
    status: 'retired',
    description: 'Ex-Champion (2024). Ausgemustert – wird durch Hermes 3 3B und Qwen3.5 abgelöst.',
    strengths: ['Solide Baseline', 'Gute Sprachqualität'],
    weaknesses: ['Von neueren Generationen überholt']
  },
  { 
    id: 'gemma-2-2b-it-q4f16_1-MLC', 
    name: 'Gemma 2 2B', 
    type: 'text',
    loader: 'mlc',
    arena: false,
    size: '2B Param', 
    cached: false, 
    loading: false, 
    progress: 0, 
    score: 1280,
    backend: 'webgpu',
    category: 'Archiv',
    badge: 'Retired',
    status: 'retired',
    description: 'Googles 2B-Modell (2024). Ausgemustert – abgelöst durch Gemma 3 1B und Qwen3.5 2B.',
    strengths: ['Früherer Reasoning-König', 'Präziser Output'],
    weaknesses: ['Von neueren Generationen überholt']
  },
  { 
    id: 'SmolLM2-1.7B-Instruct-q4f16_1-MLC', 
    name: 'SmolLM2', 
    type: 'text',
    loader: 'mlc',
    arena: false,
    size: '1.7B Param', 
    cached: false, 
    loading: false, 
    progress: 0, 
    score: 1250,
    backend: 'webgpu',
    category: 'Archiv',
    badge: 'Retired',
    status: 'retired',
    description: 'STEM-Spezialist (2024). Ausgemustert – abgelöst durch Qwen3 1.7B.',
    strengths: ['Früher stark in Mathe & Logik', 'Hohe Faktentreue'],
    weaknesses: ['Von Qwen3 klar überholt']
  },
  { 
    id: 'Llama-3.2-1B-Instruct-q4f16_1-MLC', 
    name: 'Llama 3.2 1B', 
    type: 'text',
    loader: 'mlc',
    arena: false,
    size: '1B Param', 
    cached: false, 
    loading: false, 
    progress: 0, 
    score: 1200,
    backend: 'webgpu',
    category: 'Archiv',
    badge: 'Retired',
    status: 'retired',
    description: 'Meta Allrounder (2024). Ausgemustert – abgelöst durch Gemma 3 1B und Qwen3 1.7B.',
    strengths: ['Solide Baseline', 'Gute Kontext-Stabilität'],
    weaknesses: ['Logik schwächer als neue Generation']
  },
  { 
    id: 'Qwen2.5-1.5B-Instruct-q4f16_1-MLC', 
    name: 'Qwen 2.5 1.5B', 
    type: 'text',
    loader: 'mlc',
    arena: false,
    size: '1.5B Param', 
    cached: false, 
    loading: false, 
    progress: 0, 
    score: 1180,
    backend: 'webgpu',
    category: 'Archiv',
    badge: 'Retired',
    status: 'retired',
    description: 'Alibaba Effizienz-Modell (2024). Ausgemustert – abgelöst durch Qwen3 1.7B.',
    strengths: ['Gute Mehrsprachigkeit', 'Kompakt'],
    weaknesses: ['Begrenztes Weltwissen']
  },
  { 
    id: 'Qwen2.5-0.5B-Instruct-q4f16_1-MLC', 
    name: 'Qwen 2.5 Tiny', 
    type: 'text',
    loader: 'mlc',
    arena: false,
    size: '0.5B Param', 
    cached: false, 
    loading: false, 
    progress: 0, 
    score: 1100,
    backend: 'webgpu',
    category: 'Archiv',
    badge: 'Retired',
    status: 'retired',
    description: 'Effizienz-Tiny (2024). Ausgemustert – die 2026er-Modelle schlagen es in jeder Disziplin.',
    strengths: ['Läuft fast überall', 'Schnellste Reaktion'],
    weaknesses: ['Wenig Weltwissen']
  },
  { 
    id: 'TinyLlama-1.1B-Chat-v1.0-q4f16_1-MLC', 
    name: 'TinyLlama', 
    type: 'text',
    loader: 'mlc',
    arena: false,
    size: '1.1B Param', 
    cached: false, 
    loading: false, 
    progress: 0, 
    score: 1000,
    backend: 'webgpu',
    language: 'English',
    license: 'MIT',
    category: 'Archiv',
    badge: 'Retired',
    status: 'retired',
    description: 'Negativ-Beispiel (2023). Ausgemustert – diente nur als Speed-Baseline.',
    strengths: ['Extrem schnell'],
    weaknesses: ['Unbrauchbare Logik', 'Massive Halluzinationen']
  },
  // Text-to-Image Modelle (Keine Arena!)
  {
    id: 'MarkShark2/flux2-klein-4b-onnx-webgpu-q4',
    name: 'Flux.1 [dev] Klein',
    type: 'image',
    loader: 'image-pipeline',
    arena: false,
    size: '4B Param',
    cached: false,
    loading: false,
    progress: 0,
    backend: 'onnx-webgpu',
    category: 'Image-Generation',
    badge: 'Premium',
    status: 'experimental',
    description: 'Hochwertige Bildgenerierung mit Flux Architektur, optimiert für WebGPU.',
    strengths: ['Hohe Ästhetik', 'Gutes Prompt-Following'],
    weaknesses: ['Hoher VRAM-Bedarf']
  },
  {
    id: 'brad-agi/sana-0.6b-onnx-webgpu',
    name: 'Sana 0.6B',
    type: 'image',
    loader: 'image-pipeline',
    arena: false,
    size: '0.6B Param',
    cached: false,
    loading: false,
    progress: 0,
    backend: 'onnx-webgpu',
    category: 'Image-Generation',
    badge: 'Fast',
    status: 'experimental',
    description: 'Extrem effizientes und schnelles T2I Modell für den Browser.',
    strengths: ['Extrem schnell', 'Geringer VRAM-Bedarf'],
    weaknesses: ['Geringere Details als Flux']
  },
  {
    id: 'Zhare-AI/sd-1-5-webgpu',
    name: 'Stable Diffusion 1.5',
    type: 'image',
    loader: 'image-pipeline',
    arena: false,
    size: '0.8B Param',
    cached: false,
    loading: false,
    progress: 0,
    backend: 'webgpu',
    category: 'Image-Generation',
    badge: 'Classic',
    status: 'experimental',
    description: 'Der bewährte Klassiker der Bildgenerierung, läuft lokal via WebGPU.',
    strengths: ['Hohe Kompatibilität', 'Schnell'],
    weaknesses: ['Geringere Auflösung als moderne Modelle']
  }
];
